### ISSUE TITLE
Unable to userpass login vai python but cli working

### ISSUE THREAD

**Issue by emb-karan** [hvac/hvac#853] opened 2022-08-25 09:18 UTC
I am trying to use the user pass method for login but it is raising a permission error with python but userpass login working on CLI.
Here is the code
```
import hvac
client = hvac.Client(url='https://vault-cluster-public-vault-xxxxx.hashicorp.cloud:8200')
client.auth.userpass.login('dev1', 'testme' ,mount_point='userpass')
print(client.is_authenticated())
```
which raises the below error

```
raise exceptions.Forbidden(message, errors=errors, method=method, url=url)
hvac.exceptions.Forbidden: 1 error occurred:
        * permission denied

, on post https://vault-cluster-public-vault-xxxxxx.hashicorp.cloud:8200/v1/auth/userpass/login/dev1
```

but CLI login works with the same path, default policy applied.

**Comment by colin-pm** [comment] 2022-08-30 21:31
Don't use the mount_point param unless you made a custom endpoint, the default should be sufficient.

\`client.auth.userpass.login('dev1', 'testme')`

**Comment by colin-pm** [comment] 2022-08-30 21:39
After checking the code, setting the mount_point param to "userpass" is unnecessary, but is not the root cause of this issue.

**Comment by colin-pm** [comment] 2022-08-30 21:42
Is `https://vault-cluster-public-vault-xxxxx.hashicorp.cloud` a valid URL? I can't get DNS resolution for `hashicorp.cloud`.

**Comment by colin-pm** [comment] 2022-08-31 14:44
Also, @emb-karan, since you mentioned that CLI login works, to aid in debugging could you run the working CLI command with `-output-curl-string`? That way we can see the difference between the API URL HVAC uses versus the Vault CLI tool.

**Comment by briantist** [comment] 2023-02-19 02:36
Hi @emb-karan , I hope you were able to work through your issue. If not, Colin has posted some good troubleshooting steps. In the meantime I'll close this out since it's been quite a bit of time since we've heard back. If you'd like to continue troubleshooting I might recommend opening a new question, in our [Discussions Q&A section](https://github.com/hvac/hvac/discussions/categories/q-a).

**Closed by briantist** 2023-02-19 02:36 UTC
Labels: question
