### ISSUE TITLE
Bug - KV_v2 patch operation requires read capability

### ISSUE THREAD

**Issue by stuxxn** [hvac/hvac#1189] opened 2024-09-09 09:52 UTC
Vault - `v1.17.5`
hvac - `2.3.0    HashiCorp Vault API client`

The implementation of the KV_v2 engines `patch` operation  requires `read` capability, which is not required using the `vault CLI`.

Policy:
```hcl
path "poc/data/*" {
  capabilities = [ "create", "update", "patch" ]
}
```
Using CLI with the `patch` command:
```bash
vault kv patch -mount poc  data foo=message
===== Secret Path =====
poc/data/data

======= Metadata =======
Key                Value
---                -----
created_time       2024-09-09T09:37:16.370773703Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            8

```

Using `hvac` with `client.secrets.kv.v2.patch`:
```python
import hvac
from random import choices
from string import ascii_letters, digits

VAULT_ADDR="http://127.0.0.1:8200"
VAULT_USER="sa"
VAULT_KEY="hello-vault"
MOUNT_SECRET = "poc"

def rand_str(data_len = 12) -> str:
    return ''.join( choices( ascii_letters + digits, k = data_len))

def main():

    print(f"Using vault addr: {VAULT_ADDR}")
    client = hvac.Client(url=VAULT_ADDR)

    print(f"Login with user: {VAULT_USER}")
    client.auth.userpass.login(
        username=VAULT_USER, password=VAULT_KEY
    )
    print(f"Using mount point: {MOUNT_SECRET}")

    secrets = dict(
            foo= rand_str(),            
    )
    secrets["foo bar"] = rand_str()

    client.secrets.kv.v2.patch(
        mount_point = MOUNT_SECRET,
        path="data",
        secret = secrets
    )

if __name__ == "__main__":
    main()
```

```bash
python vault.py   
                                            
Using vault addr: http://127.0.0.1:8200
Login with user: sa
Using mount point: poc
Traceback (most recent call last):
  File "XXX/example/vault.py", line 42, in <module>
    main()
  File "XXX/example/vault.py", line 32, in main
    client.secrets.kv.v2.patch(
  File "XXX/lib/python3.12/site-packages/hvac/api/secrets_engines/kv_v2.py", line 224, in patch
    current_secret_version = self.read_secret_version(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX/lib/python3.12/site-packages/hvac/api/secrets_engines/kv_v2.py", line 153, in read_secret_version
    return self._adapter.get(
           ^^^^^^^^^^^^^^^^^^
  File "XXX/lib/python3.12/site-packages/hvac/adapters.py", line 146, in get
    return self.request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX/lib/python3.12/site-packages/hvac/adapters.py", line 408, in request
    response = super().request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX/lib/python3.12/site-packages/hvac/adapters.py", line 376, in request
    self._raise_for_error(method, url, response)
  File "XXX/lib/python3.12/site-packages/hvac/adapters.py", line 294, in _raise_for_error
    utils.raise_for_error(
  File "XXX/lib/python3.12/site-packages/hvac/utils.py", line 41, in raise_for_error
    raise exceptions.VaultError.from_status(
hvac.exceptions.Forbidden: 1 error occurred:
        * permission denied

, on get http://127.0.0.1:8200/v1/poc/data/data

```

Also see #270 for implementation details.

**Comment by stuxxn** [comment] 2024-09-09 09:56
Oh sorry. I didnt see #925

**Comment by stuxxn** [comment] 2024-09-09 10:21
For a workaround the following code could be used:

```python
from hvac.adapters import JSONAdapter

class CustomAdapter(JSONAdapter):

    def patch(self, url, headers=None, **kwargs):
        headers = headers or dict()
        headers["Content-Type"] = "application/merge-patch+json"
        return self.request("patch", url, headers, **kwargs)


def patch_v2(self, path, secret, mount_point="secret"):        
    from hvac import utils
    params = {
        "options": {},
        "data": secret,
    }
    
    api_path = utils.format_url(
        "/v1/{mount_point}/data/{path}", mount_point=mount_point, path=path
    )
    return self._adapter.patch(
        url=api_path,
        json=params,
    ) 

from hvac.api.secrets_engines.kv_v2 import KvV2
KvV2.patch = patch_v2


import hvac
client = hvac.Client(url=VAULT_ADDR, adapter=CustomAdapter)

secrets = dict(patch="me")
client.secrets.kv.v2.patch(
    mount_point = MOUNT_SECRET,
    path="data",
    secret = secrets
)

```

**Comment by briantist** [comment] 2024-09-09 14:38
thanks for raising this @stuxxn , I'll close this as a duplicate of #925 . Feel free to post the workaround in that issue too.

**Closed by briantist** 2024-09-09 14:38 UTC
